"""Rank families weakest-first from probe generations; write weakness_map.md.

Reads OUT_DIR/generations.jsonl (from run_probe.py). Per family:
  accuracy, n, accuracy by status (rule_found / hypothesis_formed / rule_unknown),
  mean generated tokens, truncation rate (finish_reason == "length").

CPU-only. Usage: python report.py
"""

from __future__ import annotations

import json
import os
from collections import defaultdict
from pathlib import Path

OUT_DIR = Path(os.environ.get("PROBE_OUT", "/kaggle/working/family_probe_out"))
STATUS_ORDER = ["rule_found", "hypothesis_formed", "rule_unknown"]


def pct(c: int, n: int) -> str:
    return f"{c / n * 100:.1f}%" if n else "—"


def main() -> None:
    gens = [json.loads(l) for l in open(OUT_DIR / "generations.jsonl")]
    fams: dict[str, list[dict]] = defaultdict(list)
    for g in gens:
        fams[g["family"]].append(g)

    rows = []
    for fam, gs in fams.items():
        n = len(gs)
        acc = sum(g["correct"] for g in gs) / n
        by_status = {}
        for s in STATUS_ORDER:
            ss = [g for g in gs if g["status"] == s]
            by_status[s] = (sum(g["correct"] for g in ss), len(ss))
        mean_tok = sum(g["num_gen_tokens"] for g in gs) / n
        trunc = sum(g["finish_reason"] == "length" for g in gs) / n
        rows.append((acc, fam, n, by_status, mean_tok, trunc))
    rows.sort()  # weakest first

    header = (
        f"{'family':<18} {'acc':>6} {'n':>4} "
        f"{'rule_found':>12} {'hypothesis':>12} {'unknown':>12} "
        f"{'mean_tok':>9} {'trunc':>6}"
    )
    print(header)
    print("-" * len(header))
    md = [
        "# Family weakness map (base model, official grader)",
        "",
        "Ranked weakest-first. `rule_found` / `hypothesis_formed` / `rule_unknown` columns",
        "show accuracy on problems the winning corpus solved / half-solved / failed to",
        "solve — low `rule_unknown` accuracy marks induction headroom where rule-explicit",
        "synthetic traces could help; uniformly high accuracy means no headroom.",
        "",
        "| family | acc | n | rule_found | hypothesis_formed | rule_unknown | mean gen tokens | truncation |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for acc, fam, n, by_status, mean_tok, trunc in rows:
        cells = [pct(*by_status[s]) + (f" ({by_status[s][1]})" if by_status[s][1] else "")
                 for s in STATUS_ORDER]
        print(f"{fam:<18} {acc * 100:>5.1f}% {n:>4} "
              f"{cells[0]:>12} {cells[1]:>12} {cells[2]:>12} "
              f"{mean_tok:>9.0f} {trunc * 100:>5.1f}%")
        md.append(f"| {fam} | {acc * 100:.1f}% | {n} | {cells[0]} | {cells[1]} | "
                  f"{cells[2]} | {mean_tok:.0f} | {trunc * 100:.1f}% |")

    md += [
        "",
        "## Reading guide",
        "",
        "- **Headroom = low accuracy.** Families at the top of the table are where any",
        "  new training data could actually move the hidden-set score.",
        "- **`rule_unknown` column:** accuracy on problems the 0.85 winner could not",
        "  solve programmatically. If the base model also fails these, the family's",
        "  ceiling is rule induction itself; synthetic rule-explicit traces (new rule",
        "  generators) are the right lever. If the base model passes them, the winner's",
        "  solver was the bottleneck, not the model.",
        "- **Truncation:** finish_reason=length means the model ran out of the 7,680-token",
        "  budget before boxing an answer — trace-conciseness training is the lever there,",
        "  not variant coverage.",
        "",
        "_Generated by report.py from generations.jsonl._",
    ]
    with open(OUT_DIR / "weakness_map.md", "w") as f:
        f.write("\n".join(md) + "\n")
    print(f"\nWrote {OUT_DIR / 'weakness_map.md'}")


if __name__ == "__main__":
    main()
